---
title: "RTsimpack Diary"
author: "Luis Morís"
date: "16/12/2019"

output:
  html_document:
    toc: true
    toc_depth: 2
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 16.12.2019 RTSim as package

I have decided to move all the development of this simulation into a package.

There is now a functional version of it. Initially everything is correct, but some testing is needed.

For 100.000 iterations on Stroop approximately 1.2 hours are needed.

We need to add the option of running in parallel, and the option of running in the cluster using slurm, it seems like drake has an option for that.

We also need to learn how to build and deploy the package in the cluster as well as packing the data in drake.

We need to move the data into the inst directory, as well as save as csv/feathers, and check that the naming of the variables is correct.

We also need to start developing the drake pipeline, but given the functions already available in the package that should be easy.

Check on static branching which seems a good option to run our work.

#17.12.2019
Everything is now documented.

#17.12.2019

Profiling a bit the code by passing critical code from dplyr (slow) to data.table(fast)

Now we will prepare the files so we can use them, move to inst and transform into csv. DONE!

Prepare drake pipeline and check how to include some information about what is happenning while performing the analysis.

Add cleaning to drake pipe

Decided if we want to load files inside the functions or outside them.

When we draw the distribution we don't take into account the removed trials.

In any case although numbers don't disagree much, they don't match perfectly.

Try using Stroop.Rdata from the old functions. See if it matches that way.

Upload to bitbucket.

# 18.12.2019

Drake issues it cannot have variables inside file_* or knitr_in they must be literals.

rmarkdwon::render does not play nicely only with output_file. We must provide also output_dir.
